version: '2'
services:
    newoapp1-app:
        image: newoapp1
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://newoapp1-postgresql:5432/newoapp1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    newoapp1-postgresql:
        extends:
            file: postgresql.yml
            service: newoapp1-postgresql
